## Yearly data of district of Bihar
   **with seperate attribute**

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('tempal2.txt', sep=" ",header=None)
df.columns=('jan','f','ma',"ap","ma","jun","jul","aug","sep","oct","nov","dec","la")
df_min=pd.read_csv('min_temp.txt', sep=" ",header=None)
df_min.columns=('jan','f','ma',"ap","ma","jun","jul","aug","sep","oct","nov","dec","la")

In [3]:
# wind speed in each district in every month
df_w=pd.read_csv('wind_sp.txt', sep=" ",header=None)
df_w.columns=('jan','f','ma',"ap","ma","jun","jul","aug","sep","oct","nov","dec")
df_w;

In [4]:
# Relative humidity in each district in every month
hum=pd.read_csv('humid.txt', sep=" ",header=None)
hum.columns=('jan','f','ma',"ap","ma","jun","jul","aug","sep","oct","nov","dec")
hum;

In [5]:
# cloud in the sky in each district in every month
cloud=pd.read_csv('cloud.txt', sep=" ",header=None)
cloud.columns=('jan','f','ma',"ap","ma","jun","jul","aug","sep","oct","nov","dec")
cloud;

In [6]:
# mean rainfall  in each district in every month
rain_mi=pd.read_csv('rain_min.txt', sep=" ",header=None)
rain_mi.columns=('jan','f','ma',"ap","ma","jun","jul","aug","sep","oct","nov","dec")
rain_mi;

In [7]:
# Avg. number of rainy day   in each district in every month
rainy_day=pd.read_csv('rainy_day.txt', sep=" ",header=None)
rainy_day.columns=('jan','f','ma',"ap","ma","jun","jul","aug","sep","oct","nov","dec")
rainy_day;

In [8]:
df=df[['jan','f','ma',"ap","ma","jun","jul","aug","sep","oct","nov","dec"]]
df;

In [9]:
df_min=df_min[['jan','f','ma',"ap","ma","jun","jul","aug","sep","oct","nov","dec"]]
df_min;

In [11]:
column_names = ["max_temp(c)", "min_temp(c)", "mean_windspeed(km/hr)","re_hum(%)","cloud(okta)",
                "Mean_rain(mm)","avg._no._rainyday","district"]
z = pd.DataFrame(columns = column_names)
z["max_temp(c)"]=df['jan']
z["min_temp(c)"]=df_min['jan']
z["mean_windspeed(km/hr)"]=df_w['jan']
z["re_hum(%)"]=hum['jan']
z["cloud(okta)"]=cloud["jan"]
z["district"]=["Bhagalpur","chapra","Darbhanga","Dehri","Forbesganj","Gaya","jamui","Motihari","Muzaffarpur","patna","Purnea","Raxaul","Sabour","Supaul"]
z["Mean_rain(mm)"]=rain_mi['jan'];
z["avg._no._rainyday"]=rainy_day["jan"]
z

,max_temp(c),min_temp(c),mean_windspeed(km/hr),re_hum(%),cloud(okta),Mean_rain(mm),avg._no._rainyday,district
0,24.6,11.9,4.0,78,1.6,13.4,0.9,Bhagalpur
1,22.9,10.5,2.8,79,1.1,17.0,1.2,chapra
2,23.2,9.3,1.5,68,0.8,10.9,0.8,Darbhanga
3,23.8,8.6,3.0,74,1.4,12.2,1.6,Dehri
4,23.5,9.4,3.8,83,1.2,10.6,0.7,Forbesganj
5,23.5,8.9,4.4,76,1.8,11.7,0.9,Gaya
6,24.8,11.1,3.6,81,0.6,10.7,0.9,jamui
7,22.4,8.4,3.8,81,1.0,14.2,1.4,Motihari
8,22.6,9.6,2.3,84,1.4,12.2,0.9,Muzaffarpur
9,23.3,9.1,2.6,78,1.8,10.7,1.0,patna
10,24.0,7.8,2.4,80,1.3,9.3,0.7,Purnea
11,22.8,8.1,3.5,86,2.0,20.1,1.3,Raxaul
12,23.2,7.8,3.7,82,1.5,11.1,0.9,Sabour
13,23.7,9.8,2.0,87,1.0,8.2,0.8,Supaul